# Generated by Django 3.0.6 on 2020-06-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_usuario',
            field=models.ImageField(blank=True, upload_to='fotos_usuario/%d/%m/%Y'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='site',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sobre',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
